### ISSUE TITLE
shrinkLeaf

### ISSUE THREAD

**Issue by RuixiangMa** [liumx10/ICPP-RNTree#2]
void splitLeafNode(leaf_node_t *leaf, inner_node_t *parent)
    {
        if (leaf->slot[0] > LN_SIZE / 2)
        {
             ....
        }
        else
        {
            shrinkLeaf(leaf);
        }
    }
Hey, I want to know if shrinkLeaf in the code section means node merge operation? It doesn't seem to be the node merge in its implementation.

**Comment by liumx10** [comment]
No. We do not implement node merging, similar to many in-memory B+tree implementations, e.g., Masstree.

**Comment by RuixiangMa** [comment]
ok, can you explain the shrinkLeaf in detail? I'm very confused about this intention and implementation, and can't find useful information in your paper. Thanks!

**Comment by liumx10** [comment]
shrinkLeaf is a corner case when there are too many useless logs. For example, when splitting a leaf node,  there are 60 logs in the node, but only 15 of them are active, i.e., the size of slot array is 15. In this case,  we do not have to split the leaf node to two nodes. Instead,  we can shrink the original node by removing useless logs.  

PS: Why there exist useless logs?  Because for each modification operation, it inserts a log at first; but it can fail later due to reasons like conditional write. In this case, the log is useless, but occupies a log entry.

**Comment by RuixiangMa** [comment]
THX, I  get it.
